version: "3.7"

services:
  backend:
    image: backend
    build:
      context: .
    container_name: backend
    ports:
      - "5000:8080"
    restart: on-failure
    links:
      - database
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/versatile
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_HIKARI_SCHEMA=main
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    expose:
      - 5000

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/frontend/src
    container_name: frontend

  database:
    image: postgres:latest
    container_name: database
    volumes:
      - /opt/postgres-data:/var/lib/postgresql/data
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=versatile
      - POSTGRES_SCHEMA=main
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - 5001